djangoTKD/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import HomeView, CourseListView, SignupView, FAQView, AboutView, OtherServicesView, ContactUsMessagesView, ForumView, ForumRoomCreateView, ForumRoomView, check_username, check_email
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
	path('', HomeView.as_view(), name='index'),
	path('admin/', admin.site.urls),
	path('faq/', FAQView.as_view(), name='faq'),
	path('about/', AboutView.as_view(), name='about'),
	path('other-services/', OtherServicesView.as_view(), name='other-services'),
	path('users/', include('users.urls', namespace='users')),
	path('courses/', CourseListView.as_view(), name='courses'),
	path('forum/', ForumView.as_view(), name='forum'),
	path('forum/room/create/', ForumRoomCreateView.as_view(), name='create-room'),
	path('forum/room/<int:pk>/', ForumRoomView.as_view(), name='room'),
	path('contact-us-messages/', ContactUsMessagesView.as_view(), name='contact-us-messages'),
	path('signup/', SignupView.as_view(), name='signup'),
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
	path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

htmx_urlpatterns = [
	path('check_username/', check_username, name="check-username"),
	path('check_email/', check_email, name="check-email"),
]

urlpatterns += htmx_urlpatterns

users/urls.py
from django.urls import path
from .views import UserProfileListView, ProfileView, ProfileUpdateView, UserProfileDetailView, ThreadView, ThreadListView

app_name = 'users'

urlpatterns = [
	path('', UserProfileListView.as_view(), name='user-list'),
	path('profile/', ProfileView.as_view(), name='profile'),
	path('profile/edit/<slug:slug>/', ProfileUpdateView.as_view(), name='profile-edit'),
	path('profile/<slug:slug>/', UserProfileDetailView.as_view(), name='user-profile'),
	path('inbox/', ThreadListView.as_view(), name='inbox'),
	path('message/<slug:slug>/', ThreadView.as_view(), name='thread'),
]

users/forms.py
import logging

from betterforms.multiform import MultiModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField, UserChangeForm
from .models import MyUser, UserProfile, ContactUs, DirectMessage, ForumRoom, ForumMessage, ProfileSettings


class CustomUserCreationForm(UserCreationForm):
	password1 = forms.CharField(max_length=255, widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password'}))
	password2 = forms.CharField(max_length=255, widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password again'}))
	
	class Meta:
		model = MyUser
		fields = ('username', 'email', 'password1', 'password2')  # 'hx-swap': "outerHTML"}
		field_classes = {'username': UsernameField, }
		widgets = {
			'username': forms.TextInput(
				attrs={'placeholder': 'Enter a username', 'hx-post': "/check_username/", 'hx-swap': "outerHTML", 'hx-trigger': "keyup changed delay:500ms", 'hx-target': "#username-error"}),
			'email': forms.EmailInput(
				attrs={'placeholder': 'Enter your email', 'hx-post': "/check_email/", 'hx-swap': "outerHTML", 'hx-trigger': "keyup changed delay:500ms", 'hx-target': "#email-error"}),
		}
	
	def clean_username(self, *args, **kwargs):
		username = self.cleaned_data.get('username')
		if 'fuc' in username:
			raise forms.ValidationError('Not a valid username')
		return username
	
	def clean_email(self, *args, **kwargs):
		email = self.cleaned_data.get('email')
		if 'fuc' in email:
			raise forms.ValidationError('Not a valid email')
		return email


class CustomUserUpdateForm(UserChangeForm):
	class Meta:
		model = MyUser
		fields = ('username', 'email')
		field_classes = {'username': UsernameField, }


class UserProfileUpdateModelForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = (
			'first',
			'last',
			'phone',
			'location',
			'about',
		)
		widgets = {
			'first': forms.TextInput(attrs={'placeholder': 'Enter your first name'}),
			'last': forms.TextInput(attrs={'placeholder': 'Enter your last name'}),
			'phone': forms.TextInput(attrs={'placeholder': 'Enter your phone number'}),
			'location': forms.TextInput(attrs={'placeholder': 'Enter your city/state'}),
			'about': forms.Textarea(attrs={'placeholder': 'Enter something about yourself'}),
		}


class ProfileSettingsModelForm(forms.ModelForm):
	class Meta:
		model = ProfileSettings
		exclude = ('settings',)
		widgets = {
			'show_email': forms.CheckboxInput(attrs={'title': 'Checking this box makes your email show on your public profile page'}),
			'show_last': forms.CheckboxInput(attrs={'title': 'Checking this box makes your last name show on your public profile page'}),
			'show_phone': forms.CheckboxInput(attrs={'title': 'Checking this box makes your phone number show on your public profile page'}),
			'show_location': forms.CheckboxInput(attrs={'title': 'Checking this box makes your location show on your public profile page'}),
			'show_about': forms.CheckboxInput(attrs={'title': 'Checking this box makes your about-me show on your public profile page'}),
		}


class ProfileEditMultiForm(MultiModelForm):
	form_classes = {
		'profile': UserProfileUpdateModelForm,
		'settings': ProfileSettingsModelForm,
	}


class ContactUsForm(forms.ModelForm):
	class Meta:
		model = ContactUs
		fields = (
			'name',
			'email',
			'subject',
			'message',
		)
		widgets = {
			'name': forms.TextInput(attrs={'placeholder': 'Enter your name'}),
			'email': forms.EmailInput(attrs={'placeholder': 'Enter your email'}),
			'subject': forms.TextInput(attrs={'placeholder': 'Enter the subject'}),
			'message': forms.Textarea(attrs={'placeholder': 'Type your message here'}),
		}


class DirectMessageForm(forms.ModelForm):
	class Meta:
		model = DirectMessage
		fields = (
			'message',
		)
		widgets = {'message': forms.Textarea(attrs={'placeholder': 'Enter a message, then click Send.'})}


class ForumRoomForm(forms.ModelForm):
	class Meta:
		model = ForumRoom
		fields = (
			'title',
			'description',
		)
		widgets = {
			'title': forms.TextInput(attrs={'placeholder': 'Enter a title'}),
			'description': forms.Textarea(attrs={'placeholder': 'Enter a description'})
		}


class ForumMessageForm(forms.ModelForm):
	class Meta:
		model = ForumMessage
		fields = (
			'body',
		)
		widgets = {'body': forms.Textarea(attrs={'placeholder': 'Enter a message, then click Post.'})}

users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import reverse, redirect
from django.template.response import TemplateResponse
from django.views import generic
from .models import UserProfile, Course, ContactUs, DirectMessageThread, DirectMessage, ForumRoom, ForumMessage
from .forms import CustomUserCreationForm, ContactUsForm, DirectMessageForm, ForumRoomForm, ForumMessageForm, ProfileEditMultiForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class SignupView(generic.CreateView):
	template_name = 'registration/signup.html'
	form_class = CustomUserCreationForm
	
	def get_success_url(self):
		messages.add_message(self.request, messages.INFO, 'Account created, please log in.')
		return reverse('login')


class HomeView(generic.CreateView):
	template_name = 'index.html'
	form_class = ContactUsForm
	
	def get_success_url(self):
		messages.add_message(self.request, messages.INFO, 'Thank you for contacting us.')
		return reverse('index') + '#'


class FAQView(generic.TemplateView):
	template_name = 'faq.html'


class AboutView(generic.TemplateView):
	template_name = 'about.html'


class OtherServicesView(generic.TemplateView):
	template_name = 'other_services.html'


class UserProfileListView(generic.ListView):
	template_name = 'users/user_list.html'
	queryset = UserProfile.objects.all()
	context_object_name = 'profiles'


class ProfileView(LoginRequiredMixin, generic.ListView):
	template_name = 'users/profile.html'
	
	def get_queryset(self):
		user = self.request.user
		return user


class ProfileUpdateView(LoginRequiredMixin, generic.UpdateView):
	template_name = 'users/profile_edit.html'
	form_class = ProfileEditMultiForm
	
	def get_form_kwargs(self):
		kwargs = super().get_form_kwargs()
		kwargs.update(instance={
			'profile': self.object,
			'settings': self.object.settings,
		})
		return kwargs
	
	def get_queryset(self):
		user = self.request.user
		queryset = UserProfile.objects.filter(user=user)
		return queryset
	
	def get_success_url(self):
		messages.add_message(self.request, messages.INFO, 'Updated successfully.')
		return reverse('users:profile')


class UserProfileDetailView(LoginRequiredMixin, generic.DetailView):
	template_name = 'users/user_profile.html'
	model = UserProfile


# def get_context_data(self, **kwargs):
# 	context = super().get_context_data(**kwargs)
# 	return context


class CourseListView(generic.ListView):
	template_name = 'users/course_list.html'
	queryset = Course.objects.all()
	context_object_name = 'courses'


class ContactUsMessagesView(UserPassesTestMixin, generic.ListView):
	template_name = 'contact_us_messages.html'
	queryset = ContactUs.objects.all()
	
	def test_func(self):
		return self.request.user.is_superuser


class ThreadListView(LoginRequiredMixin, generic.View):
	
	def get_queryset(self, request):
		return DirectMessageThread.objects.filter(Q(user=request.user.profile) | Q(receiver=request.user.profile))
	
	def get(self, request, *args, **kwargs):
		threads = self.get_queryset(request=request)
		
		context = {
			'threads': threads,
		}
		
		return TemplateResponse(request, 'users/inbox.html', context)


class ThreadView(LoginRequiredMixin, generic.View):
	
	def get(self, request, slug, *args, **kwargs):
		form = DirectMessageForm()
		receiver = UserProfile.objects.filter(slug=slug)[0]
		thread = DirectMessageThread.objects.filter(user=request.user.profile, receiver=receiver).first() or DirectMessageThread.objects.filter(user=receiver, receiver=request.user.profile).first()
		if thread:
			direct_messages = DirectMessage.objects.filter(thread=thread)
			context = {
				'form': form,
				'thread': thread,
				'direct_messages': direct_messages,
			}
			
			return TemplateResponse(request, 'users/thread.html', context)
		else:
			thread = DirectMessageThread(
				user=request.user.profile,
				receiver=receiver,
			)
			thread.save()
			return redirect('users:thread', slug)
	
	def post(self, request, slug, *args, **kwargs):
		form = DirectMessageForm(request.POST)
		message = request.POST.get('message')
		receiver = UserProfile.objects.filter(slug=slug)[0]
		thread = DirectMessageThread.objects.filter(user=request.user.profile, receiver=receiver).first() or DirectMessageThread.objects.filter(user=receiver, receiver=request.user.profile).first()
		
		if form.is_valid() and message:
			new_message = DirectMessage(
				thread=thread,
				sender=request.user.profile,
				receiver=receiver,
				message=message,
			)
			new_message.save()
			messages.add_message(self.request, messages.INFO, 'Message sent successfully.')
			return redirect('users:thread', slug)
		
		return TemplateResponse(request, 'users/thread.html')


class ForumView(LoginRequiredMixin, generic.ListView):
	template_name = 'users/forum.html'
	context_object_name = 'rooms'
	
	def get_queryset(self):
		return ForumRoom.objects.all()
	
	def get_context_data(self, object_list=None, **kwargs):
		context = super().get_context_data(**kwargs)
		context['my_rooms'] = ForumRoom.objects.filter(participants__user=self.request.user)
		return context


class ForumRoomCreateView(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
	template_name = 'users/forum_room_create.html'
	form_class = ForumRoomForm
	success_message = 'Successfully created a room'
	
	def form_valid(self, form):
		room = form.save(commit=False)
		room.host = self.request.user.profile
		room = form.save()
		room.participants.add(self.request.user.profile.id)
		room.save()
		self.kwargs['pk'] = room.id
		return super(ForumRoomCreateView, self).form_valid(form)
	
	def get_success_url(self):
		return reverse('room', kwargs={'pk': self.kwargs['pk']})


class ForumRoomView(LoginRequiredMixin, generic.View):
	
	def get(self, request, pk, *args, **kwargs):
		form = ForumMessageForm()
		room = ForumRoom.objects.filter(id=pk).first()
		comments = ForumMessage.objects.filter(room_id=pk)
		if room:
			context = {
				'form': form,
				'room': room,
				'comments': comments,
			}
			return TemplateResponse(request, 'users/room.html', context)
		
		else:
			return redirect('forum')
	
	def post(self, request, pk, *args, **kwargs):
		form = ForumMessageForm(request.POST)
		room = ForumRoom.objects.filter(id=pk).first()
		body = request.POST.get('body')
		room.participants.add(self.request.user.profile.id)
		
		if form.is_valid():
			new_message = ForumMessage(
				user=self.request.user.profile,
				room=room,
				body=body,
			)
			new_message.save()
			messages.add_message(request, messages.INFO, 'Comment posted successfully.')
			return redirect('room', pk=room.id)


def check_username(request):
	username = request.POST.get('username')
	if username:
		if get_user_model().objects.filter(username=username).exists():
			return HttpResponse('<div id="username-error" style="color:red">Username taken</div>')
		else:
			return HttpResponse('<div id="username-error" style="color:green">Username available</div>')
	else:
		return HttpResponse('<div id="username-error">&nbsp;</div>')


def check_email(request):
	email = request.POST.get('email')
	if email:
		if get_user_model().objects.filter(email=email).exists():
			return HttpResponse('<div id="email-error" style="color:red">Email taken</div>')
		else:
			return HttpResponse('<div id="email-error" style="color:green">Email available</div>')
	else:
		return HttpResponse('<div id="email-error">&nbsp;</div>')
	
	

users/templates/users/course_list.html
{% extends 'base.html' %}
{% block title %}Courses |{% endblock title %}
{% block content %}

	<div>
		<table>
			<tr>
				<th>name</th>
				<th>time</th>
				<th>ages</th>
				<th>cost</th>
				<th>description</th>
				<th>instructor</th>
			</tr>
			{% for course in courses %}
				<tr>
					<td>{{ course.name }}</td>
					<td>{{ course.time }}</td>
					<td>{{ course.ages }}</td>
					<td>{{ course.cost }}/{{ course.billing }}</td>
					<td>{{ course.description }}</td>
					<td>{%  for instructor in course.instructor.all %}{{ instructor.last }}{% endfor %}</td>
				</tr>
			{% endfor %}
		</table>
	</div>

{% endblock %}

users/templates/users/create_thread.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}{% endblock title %}

{% block content %}
	<div class="container">

		<div class="row">
			<div><a href="{% url 'users:inbox' %}">Back to inbox.</a></div>
		</div>

		<div class="row">
			<div>Start a Conversation.</div>
		</div>

		<div class="row">
			<div>
				<form method="POST">
					{% csrf_token %}
					<p>Enter Message</p>
					{{ form|crispy }}
					<button type="submit">Send</button>
				</form>
			</div>
		</div>

	</div>
{% endblock content %}

users/templates/users/forum.html
{% extends 'base.html' %}
{% block title %}Forum |{% endblock title %}

{% block content %}
	<div>
		<div>
			<a href="{% url 'create-room' %}"><h5>Create New Room</h5></a>
			<br>
		</div>
		<div>
			{% for room in rooms %}
				<h2><a href="{% url 'room' room.id %}">{{ room.title }}</a></h2>
				<p>{{ room.description }}</p>
				<p>{{ room.created }}</p>
				<br>
			{% endfor %}
		</div>
		<div>
			<h1 style="color: crimson">My Activity</h1>
		</div>
		<div>
			{% for room in my_rooms %}
				<h2><a href="{% url 'room' room.id %}">{{ room.title }}</a></h2>
				<p>{{ room.description }}</p>
			{% endfor %}
		</div>
	</div>
{% endblock content %}

users/templates/users/forum_room_create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block title %}Room |{% endblock title %}

{% block content %}
	<div>
		<div>

		</div>
		<div>
			<form method="POST">
				<div>
					<div>
						{{ form|crispy }}
						{% csrf_token %}
					</div>
					<div>
						<button type="submit">Create Room</button>
					</div>
				</div>
			</form>
		</div>
		<div>

		</div>
	</div>
{% endblock content %}

users/templates/users/inbox.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block content %}
	<div class="container">
		<div class="row">
			<div>Your Conversations</div>
		</div>
		<div class="row">
			<div>
{#				<form method="GET" action="{% url 'users:create-thread' %}">#}
{#					<button type="submit">Start a Conversation</button>#}
{#				</form>#}
			</div>
		</div>
		{% for thread in threads %}
			<div class="row">
				<div>
					{% if thread.user.user.username == request.user.username %}
						<a href="{% url 'users:thread' thread.receiver.slug %}"><h2>@{{ thread.receiver.user.username }} ({{ thread.receiver.first }})</h2></a>
					{% elif thread.receiver.user.username == request.user.username %}
						<a href="{% url 'users:thread' thread.user.user.profile.slug %}"><h2>@{{ thread.user.user.username }} ({{ thread.user.first }})</h2></a>
					{% endif %}
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}My Profile |{% endblock %}

{% block content %}
	<div>
		<div>
			<h2>@{{ user.username }}</h2>
			<br>
			<h2>{{ user.email }}</h2>
			<h2>{{ user.profile.first }} {{ user.profile.last }}</h2>
			<h2>{{ user.profile.phone }}</h2>
			<h2>{{ user.profile.location }}</h2>
			<h2>{{ user.profile.about }}</h2>
		</div>
		<div>
			<div>
				<a href="{% url 'users:user-profile' user.profile.slug %}">My public profile</a>
			</div>
			<div>
				<a href="{% url 'users:profile-edit' user.profile.slug %}">Edit my profile</a>
			</div>
		</div>
	</div>
{% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Edit My Profile |{% endblock %}

{% block content %}
	<div>
		<div>
			<form action="" method="POST">
				{% csrf_token %}
				<div>
					<h2>@{{ object.user.username }}</h2>
					<p>{{ form.profile.first }}</p>
					<p>Username and first name are always visible</p>
				</div>
				<br>
				<div>
					<p>{{ form.profile.last }}</p>
					<p style="width: 20px">{{ form.settings.show_last }} Share my last name</p>
				</div>
				<br>
				<div>
					<p>{{ object.user.email }}</p>
					<p style="width: 20px">{{ form.settings.show_email }} Share my email</p>
				</div>
				<br>
				<div>
					<p>{{ form.profile.phone }}</p>
					<p style="width: 20px">{{ form.settings.show_phone }} Share my phone number</p>
				</div>
				<br>
				<div>
					<p>{{ form.profile.location }}</p>
					<p style="width: 20px">{{ form.settings.show_location }} Share my location</p>
				</div>
				<br>
				<div>
					<p>{{ form.profile.about }}</p>
					<p style="width: 20px">{{ form.settings.show_about }} Share something about me</p>
				</div>
				<button type="submit">Submit</button>
				<a href="{% url 'users:profile' %}">
					<button type="button">Cancel</button>
				</a>
			</form>
		</div>
	</div>
{% endblock content %}

users/templates/users/room.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Room |{% endblock title %}

{% block content %}
	<div>
		<div>
			<p><a href="{% url 'forum' %}">Back to Forum</a></p>
		</div>
		<div>
			<h2>{{ room.title }}</h2>
			<p>{{ room.description }}</p>
			<p><a href="{% url 'users:user-profile' room.host.slug %}">{{ room.host }}</a></p>
			<p>{{ room.created }}</p>
		</div>
		<div>
			{% for comment in comments %}
				<div>
					<p style="white-space: normal">{{ comment }}</p>
					<p><a href="{% url 'users:user-profile' comment.user.slug %}">@{{ comment.user.user.username }}</a></p>
					<p>{{ comment.user.first }}</p>
					<p>{{ comment.created }}</p>
				</div>
			{% endfor %}
		</div>
		<div>
			<form method="POST">
				<div>
					<div>
						{{ form|crispy }}
						{% csrf_token %}
					</div>
					<div>
						<button type="submit">Post</button>
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock content %}

users/templates/users/thread.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block title %}{% endblock title %}

{% block content %}
	<div class="container">
		<div class="row">
			<div>
				{% if thread.receiver == request.user.profile %}
					<h2 style="color: coral">@{{ thread.user.user.username }}</h2>
					<h25 style="color: coral">{{ thread.user }}</h25>
				{% else %}
					<h2 style="color: coral">@{{ thread.receiver.user.username }}</h2>
					<h5 style="color: coral">{{ thread.receiver }}</h5>
				{% endif %}
			</div>
		</div>

		{% if direct_messages.all.count == 0 %}
		<div class="row">
			<div>
				<h3>No Messages</h3>
			</div>
		</div>
		{% endif %}

		{% for direct_message in direct_messages %}
		<div class="row">
			{% if direct_message.sender == request.user.profile %}
			<p style="color: aquamarine">{{ direct_message.message }}</p>
			{% else %}
			<p style="color: coral">{{ direct_message.message }}</p>
			{% endif %}
		</div>
		{% endfor %}
		<div>
			<form method="POST">
				{{ form|crispy }}
				{% csrf_token %}
				<button type="submit">Send</button>
			</form>
		</div>
	</div>
{% endblock content %}

users/templates/users/user_list.html
{% extends 'base.html' %}
{% block title %}Users |{% endblock title %}
{% block content %}

	<div>
		<table>
			<tr>
				<th>username</th>
				<th>first</th>
				<th>last</th>
				<th>location</th>
				<th>instructor</th>
			</tr>
			{% for profile in profiles %}
				<tr>
					<td><a href="{% url 'users:user-profile' profile.slug %}">{{ profile.user.username }}</a></td>
					<td>{{ profile.first }}</td>
					<td>{{ profile.last }}</td>
					<td>{{ profile.location }}</td>
					<td>
						{% if profile.is_instructor %}
							Yes
						{% else %}
						{% endif %}
					</td>
				</tr>
			{% endfor %}
		</table>
	</div>

{% endblock %}

users/templates/users/user_profile.html
{% extends 'base.html' %}

{% block title %}
	{% if object.first %}
	{{ object.first }}'s Profile |
	{% else %}
	{{ object.user.username }}'s Profile |
	{% endif %}
{% endblock %}
{% block content %}
	<div>
		<div>
			<h2>@{{ object.user.username }}</h2>
			<br>
			{% if object.settings.show_email %}
			<h2>{{ object.user.email }}</h2>
			{% endif %}
			<h2>
				{{ object.first }}
				{% if object.settings.show_last %}
					{{ object.last }}
				{% endif %}
			</h2>
			{% if object.settings.show_phone %}
			<h2>{{ object.phone }}</h2>
			{% endif %}
			{% if object.settings.show_location %}
			<h2>{{ object.location }}</h2>
			{% endif %}
			{% if object.settings.show_about %}
			<h2>{{ object.about }}</h2>
			{% endif %}
		</div>
	<div>
		<div>
			<a href="{% url 'users:profile' %}">My private profile</a>
		</div>
		{% if not object.user.username == request.user.username %}
			<div>
				<a href="{% url 'users:thread' object.slug %}">
					{% if object.first %}
						Send {{ object.first }} a private message.
					{% else %}
						Send @{{ object.user.username }} a private message.
					{% endif %}
				</a>
			</div>
		{% endif %}
	</div>
	</div>
{% endblock %}