djangoTKD/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import HomeView, CourseListView, SignupView, FAQView, AboutView, OtherServicesView, ContactUsMessagesView, ForumView, ForumRoomCreateView, ForumRoomView, check_username, check_email
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
	path('', HomeView.as_view(), name='index'),
	path('admin/', admin.site.urls),
	path('faq/', FAQView.as_view(), name='faq'),
	path('about/', AboutView.as_view(), name='about'),
	path('other-services/', OtherServicesView.as_view(), name='other-services'),
	path('users/', include('users.urls', namespace='users')),
	path('courses/', CourseListView.as_view(), name='courses'),
	path('forum/', ForumView.as_view(), name='forum'),
	path('forum/room/create/', ForumRoomCreateView.as_view(), name='create-room'),
	path('forum/room/<int:pk>/', ForumRoomView.as_view(), name='room'),
	path('contact-us-messages/', ContactUsMessagesView.as_view(), name='contact-us-messages'),
	path('signup/', SignupView.as_view(), name='signup'),
	path('login/', LoginView.as_view(), name='login'),
	path('logout/', LogoutView.as_view(), name='logout'),
	path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
	path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

htmx_urlpatterns = [
	path('check_username/', check_username, name="check-username"),
	path('check_email/', check_email, name="check-email"),
]

urlpatterns += htmx_urlpatterns

users/urls.py
from django.urls import path
from .views import UserProfileListView, ProfileView, ProfileUpdateView, UserProfileDetailView, ThreadView, ThreadListView

app_name = 'users'

urlpatterns = [
	path('', UserProfileListView.as_view(), name='user-list'),
	path('profile/', ProfileView.as_view(), name='profile'),
	path('profile/edit/<slug:slug>/', ProfileUpdateView.as_view(), name='profile-edit'),
	path('profile/<slug:slug>/', UserProfileDetailView.as_view(), name='user-profile'),
	path('inbox/', ThreadListView.as_view(), name='inbox'),
	path('message/<slug:slug>/', ThreadView.as_view(), name='thread'),
]

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About |{% endblock %}

{% block content %}

	<div class="about_div">

		<div>

			<div style="text-align: center;">
				<span>About Us</span>
			</div>

			<div>
				<div>The study of Tae Kwon Do (art of
					foot and hand) is an undertaking that offers both physical and mental
					rewards. We have six tenets upon which we base our training: modesty, perseverance, self control,
					indomitable spirit, courtesy and integrity. All classes are taught by certified Black Belt
					instructors.
				</div>
				<div>Young’s Tae Kwon Do is the
					regional headquarters for the <span>International Chin Mu Kwan Tae Kwon Do
				federation</span> which has schools and instructors all around the world. This federation was founded by
					9th
					degree Black Belt Grand Master Yon Ho Kang. The Pennsylvania headquarters is located in Conshohocken
					and
					is run by 9th degree Black Belt, Grand Master Fred DeStolfo (Grand Master Young’s instructor). PA
					branch
					schools are located in Bellefonte, Danville, Selinsgrove, Blairsville, Norristown, Huntington,
					Halifax,
					Altoona, Coudersport , and Glenmoore. Any Young’s students may travel to any branch school and be
					welcomed with open arms.
				</div>
			</div>
		</div>

		<div>
			<img src="{% static 'images/11062b_660ab66366b24a29bcb1212876d0a740_mv2.webp' %}"
				 alt="Martial Arts Training">
		</div>

		<div style="display: flex">

			<div style="width: 50%">
				<div>
					<div>
						<div>Chin Mu Kwan Federation</div>
						<div>Chin Mu Kwan literally means “True Martial Art Home” the art of Taekwon-Do as a self defense.</div>
						<div>We do the Chang Hon (Blue Cottage) forms, we do the original set of forms which has Ko-Dang at 4th degree, we do not do the form Juche. Consult the CTF Rules and Regulations for order of forms. The various TKD forms CD’s and books are for reference only and are not a replacement for a certified CTF instructor.</div>
						<div>Chin Mu Kwan Taekwon-Do became a Federation (CTF) in 1966 around the same time the International Taekwon-Do Federation  (ITF) was formed. CTF is dedicated to promoting traditional Taekwon-Do, to maintain the highest standards and certifications in Taekwon-Do.</div>
					</div>
				</div>
			</div>
			<div style="width: 50%">
				<img src="{% static 'images/971821_c1aa866a16534537b85d5a4afc7aefb0_mv2.webp' %}" alt="CTFLogo.jpg">
			</div>

		</div>

		<div style="display: flex">

			<div style="width: 50%">
				<img src="{% static 'images/971821_65241041e36f42759f5f8c0f74388f7b_mv2.webp' %}" alt="school.jpg">
			</div>
			<div style="width: 50%">
				<div>
					<div>Young's TKD in Bellefonte</div>
					<div>Young's TKD was founded in 1980 by Michael Young. Since then, we have grown and added many more members and martial arts groups to our school.  Young's TKD prides it's self on being an active part of the Bellefonte community.  We also hold a twice yearly tournament at the Bellefonte High School in the spring and fall.</div>
				</div>
			</div>

		</div>

		<div style="display: flex">

			<div style="width: 50%">
				<div>
					<div>Instructors</div>
					<div>The three main instructors at Young's TKD are Grand Master Young (9th Degree), Sensei/Master Cramer (6th Degree), and Master Rogosky (5th Degree).  There are also many other students who have earned their black belts and master instructor degrees through our federation.</div>
				</div>
			</div>
			<div style="width: 50%">
				<img src="{% static 'images/971821_f253cd8e127e4d19945413606ea1160e_mv2.webp' %}" alt="2013-12-14 12.19.28.jpg">
			</div>

		</div>


	</div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock title %} Young's TKD</title>
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
	<script src="https://unpkg.com/htmx.org@1.7.0"></script>
</head>
<body>
{% include 'navbar.html' %}
{% include 'messages.html' %}
{% block content %}
{% endblock content %}
{% include 'footer.html' %}
</body>
</html>

templates/contact_us_messages.html
{% extends 'base.html' %}

{% block title %}Contact Us Messages|{% endblock %}

{% block content %}
<div>
		<table>
			<tr>
				<th>name</th>
				<th>email</th>
				<th>subject</th>
				<th>message</th>
				<th>created</th>
			</tr>
				{% for object in object_list %}
				<tr>
					<td>{{ object.name }}</td>
					<td>{{ object.email }}</td>
					<td>{{ object.subject }}</td>
					<td>{{ object.message }}</td>
					<td>{{ object.created }}</td>
				</tr>
			{% endfor %}
		</table>
	</div>
{% endblock content %}

templates/faq.html
{% extends 'base.html' %}
{% block title %}FAQ |{% endblock %}
{% block content %}
	<div style="background-color: #19191FFF; width: 100%">
		<div id="faq_div_center" style="background-color: transparent; max-width: 70%;">

			<div style="display: flex; background-color: transparent;">
				<div>
					<span>FAQ</span>
					<p>Our Answers</p>
				</div>
			</div>

			<div id="faq_div_left">

				<div style="display: flex">
					<div class="faq_left">
						<span>Am I to old or out of shape to do martial arts?</span>
						<p>Everyone can do martial arts, and it's never too late to start. Never use the excuse "I'll
							start classes when I get in shape." We teach people of all skill and fitness levels.</p>
					</div>
				</div>

				<div style="display: flex">
					<div class="faq_left">
						<span>How do I know if martial arts is right for me?</span>
						<p>There are many great resources online. But the best way is to contact us, ask lots of
							questions, come watch a class, and/or try a free trial lesson.</p>
					</div>
				</div>

				<div style="display: flex">
					<div class="faq_left">
						<span>What do I need to know before getting started?  What is the etiquette of the school?</span>
						<p>Our school is like many other martial arts school. You're always welcome to come inside to
							the seating area. Please be patient if we are in the middle of a class. Introduce yourself
							to an instructor/black belt and ask to speak with the head instructor.</p>
						<p>When you start classes:</p>
						<ol style="list-style: upper-roman">
							<li>Take your socks and shoes off before stepping on the mat.</li>
							<li>Trim your finger/toe nails before class.</li>
							<li>Keep your uniform and yourself clean. The only exception is your belt. Belts never get
								put in the laundry or left on the floor. The only thing that should make your belt dirty
								is your hard work while it is around your waste.
							</li>
							<li>All unnecessary jewelry should be removed mainly for safety purposes.</li>
							<li>Hair should be managed appropriately, so it is not a distraction during class.</li>
						</ol>
					</div>
				</div>

				<div style="display: flex">
					<div class="faq_left">
						<span>How long does it take the average person to get a black belt?</span>
						<p>The "Average" person does not get a black belt. Black belts are earned through years of hard
							work, dedication, and study. How many years will completely depend on you.</p>
					</div>
				</div>

				<div style="display: flex">
					<div class="faq_left">
						<span>Will I need to register my hands as deadly weapons?</span>
						<p>Even though they might become deadly weapons through your dedicated training regimen, no,
							this is just a myth. That being said, it is your responsibility to only use your martial
							arts skills at the right times and situations when you are required to defend yourself and
							others.</p>
					</div>
				</div>

			</div>

		</div>
	</div>
{% endblock %}

templates/footer.html
<footer>
	<div>
		<div class="bigpad">
			<p class="large center">Young's Tae Kwon Do</p>
		</div>
		<div>
			<p class="center">
				<a href="mailto:youngstkdbellefonte@gmail.com">youngstkdbellefonte@gmail.com
				</a>
			</p>
		</div>
		<div>
			<p class="center">(814) 355-2250 (Call or Text)</p>
		</div>
		<div>
			<p class="center">219 W High St, Bellefonte, PA 16823</p>
		</div>
		<div class="bigpad">
			<p class="center">©2022 by Young's Tae Kwon Do. Proudly created with django</p>
		</div>
	</div>
</footer>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}
	<div>
		<div>
			<img class="center" src="{% static 'images/main_logo.webp' %}" alt="WebsiteMain2022">
		</div>
		<div style="display: flex">
			<div>
				<img class="adjust" src="{% static 'images/971821_431bdd60de334f88904d8e8982bbc2a9_mv2.webp' %}"
					 alt="Martial Arts Class in Progress">
			</div>
			<div>
				<img class="adjust" src="{% static 'images/971821_26c4daf4895d4f71b2bacc25329df9c6_mv2.webp' %}"
					 alt="Martial Arts Class in Progress">
			</div>
		</div>
		<div id="contact">
			<div style="display: flex">
				<div class="bigpad">
					<p class="huge left">Contact Us Today!</p>
					<p class="left">219 W High St, Bellefonte, PA 16823</p>
					<p class="left">YoungsTKDbellefonte@Gmail.com</p>
					<p class="left">(814) 355-2250 (Call or Text)</p>

					<ul style="display: flex;">
						<li>
							<a href="https://maps.google.com/?cid=17255987814215067691" target="_blank">
								<img src="{% static 'images/google_places.webp' %}" alt="Google Places">
							</a>
						</li>
						<li>
							<a href="https://www.facebook.com/youngs.tkd.bellefonte/" target="_blank">
								<img src="{% static 'images/facebook.webp' %}" alt="Facebook">
							</a>
						</li>
						<li>
							<a href="https://www.instagram.com/youngs.tkd.bellefonte/" target="_blank">
								<img src="{% static 'images/instagram.webp' %}" alt="Instagram">
							</a>
						</li>
					</ul>


					<form method="POST" id="contactform">
						<div>
						{% csrf_token %}
						{{ form|crispy }}
						</div>
						<div style="display: flex; height: 50px">
							<button type="submit" style="margin-left: auto; width: 150px; background-color: darkgray">
								Submit
							</button>
						</div>
					</form>
				</div>
				<div>
					<img src="{% static 'images/11062b_637c206a2006498e9049e714681c009a_mv2.webp' %}"
						 alt="Martial Arts Class in Progress">
				</div>
			</div>
		</div>
		<div style="display: flex">
			<span style="margin: auto">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3015.187298461366!2d-77.78259468458894!3d40.9116389793107!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xef79957daac2282b!2sYoung&#39;s%20School%20of%20Tae%20Kwon%20DO!5e0!3m2!1sen!2sus!4v1644611610712!5m2!1sen!2sus"
						width="900" height="400" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
			</span>
		</div>
	</div>
{% endblock %}


{#<div>#}
{#	<div>#}
{#		<label for="name">Name *</label>#}
{#	</div>#}
{#	<div>#}
{#		<input type="text" id="name" placeholder="Enter your name" style="width: 100%">#}
{#	</div>#}
{#	<div>#}
{#		<label for="email">Email *</label>#}
{#	</div>#}
{#	<div>#}
{#		<input type="email" id="email" placeholder="Enter your email">#}
{#	</div>#}
{#	<div>#}
{#		<label for="subject">Subject:</label>#}
{#	</div>#}
{#	<div>#}
{#		<input type="text" id="subject" placeholder="Type the subject">#}
{#	</div>#}
{#	<div>#}
{#		<label for="message">Message:</label>#}
{#	</div>#}
{#	<div>#}
{#		<input type="text" id="message" placeholder="Type your message here...">#}
{#	</div>#}
{#</div>#}

templates/messages.html
{% if messages %}
	<div>
		{% for message in messages %}
			<div style="background-color: #bbbb00; opacity: 90%;">
				<p style="background-color: #bbbb00; opacity: 90%; color: black">{{ message }}</p>
			</div>
		{% endfor %}
	</div>
{% endif %}

templates/navbar.html
{% load static %}
<header>
	<div>
		<ul style="display: flex; border-bottom: darkgray; border-bottom-style: solid">
			<li class="left">
				<a href="https://maps.google.com/?cid=17255987814215067691" target="_blank">
					<img src="{% static 'images/google_places.webp' %}" alt="Google Places">
				</a>
			</li>
			<li>
				<a href="https://www.facebook.com/youngs.tkd.bellefonte/" target="_blank">
					<img src="{% static 'images/facebook.webp' %}" alt="Facebook">
				</a>
			</li>
			<li>
				<a href="https://www.instagram.com/youngs.tkd.bellefonte/" target="_blank">
					<img src="{% static 'images/instagram.webp' %}" alt="Instagram">
				</a>
			</li>
		</ul>
	</div>
	<div>
		<ul style="display: flex">
			<li>
				<a href="{% url 'index' %}">
					<img src="{% static 'images/tkd_logo.webp' %}" alt="TKD logo">
				</a>
			</li>
			<li>
				<a href="{% url 'index' %}">
					<p class="large">Young's Tae Kwon Do</p>
				</a>
				<p>Get started on your martial arts journey today!</p>
			</li>
			<li class="left"><a href="{% url 'index' %}">Home</a></li>
			<li><a href="{% url 'index' %}#contact">Contact Us</a></li>
			<li><a href="{% url 'courses' %}">Classes</a></li>
			<li><a href="{% url 'faq' %}">FAQ</a></li>
			<li><a href="{% url 'about' %}">About</a></li>
			<li><a href="{% url 'other-services' %}">Other Services</a></li>
			{% if user.is_authenticated %}
				<li><a href="{% url 'users:user-list' %}">Users</a></li>
				<li><a href="{% url 'users:inbox' %}">Inbox</a></li>
				<li><a href="{% url 'forum' %}">Forum</a></li>
				<li><a href="{% url 'users:profile' %}">My Profile</a></li>
				{% if user.is_superuser %}
					<li><a href="{% url 'contact-us-messages' %}">Contact-us Messages</a></li>
				{% endif %}
				<li><a href="{% url 'logout' %}">Logout</a></li>
			{% else %}
				<li><a href="{% url 'login' %}">Login</a></li>
				<li><a href="{% url 'signup' %}">Sign Up</a></li>
			{% endif %}
		</ul>
	</div>
</header>

templates/other_services.html
{% extends 'base.html' %}

{% block title %}Services |{% endblock %}

{% block content %}


{% endblock %}